/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountBtn: typeof import('./src/components/window/AccountBtn.vue')['default']
    AppBar: typeof import('./src/components/window/AppBar.vue')['default']
    AvatarBtn: typeof import('./src/components/window/AvatarBtn.vue')['default']
    BatchUsers: typeof import('./src/components/accounts/BatchUsers.vue')['default']
    CheckingForUpdates: typeof import('./src/components/CheckingForUpdates.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ModelRender: typeof import('./src/components/model/ModelRender.vue')['default']
    OrgsBtn: typeof import('./src/components/accounts/OrgsBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFields: typeof import('./src/components/search/SearchFields.vue')['default']
    SearchPalettes: typeof import('./src/components/search/SearchPalettes.vue')['default']
    SelectionOrgs: typeof import('./src/components/accounts/selection/SelectionOrgs.vue')['default']
    ShoppingCarts: typeof import('./src/components/ShoppingCarts.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    UgglyBunny: typeof import('./src/components/model/UgglyBunny.vue')['default']
  }
}
