/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/window/AppBar.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFields: typeof import('./src/components/search/SearchFields.vue')['default']
    SearchPalettes: typeof import('./src/components/search/SearchPalettes.vue')['default']
    ShoppingCarts: typeof import('./src/components/ShoppingCarts.vue')['default']
    Snackbar: typeof import('./src/components/Snackbar.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
