/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//about': RouteRecordInfo<'//about', '/about', Record<never, never>, Record<never, never>>,
    '//accounts/orgs': RouteRecordInfo<'//accounts/orgs', '/accounts/orgs', Record<never, never>, Record<never, never>>,
    '//accounts/roles': RouteRecordInfo<'//accounts/roles', '/accounts/roles', Record<never, never>, Record<never, never>>,
    '//accounts/users.[[rids]]': RouteRecordInfo<'//accounts/users.[[rids]]', '/accounts/users/:rids?', { rids?: ParamValueZeroOrOne<true> }, { rids?: ParamValueZeroOrOne<false> }>,
    '//ai/chat': RouteRecordInfo<'//ai/chat', '/ai/chat', Record<never, never>, Record<never, never>>,
    '//ai/knowledge-library': RouteRecordInfo<'//ai/knowledge-library', '/ai/knowledge-library', Record<never, never>, Record<never, never>>,
    '//ai/live': RouteRecordInfo<'//ai/live', '/ai/live', Record<never, never>, Record<never, never>>,
    '//contact': RouteRecordInfo<'//contact', '/contact', Record<never, never>, Record<never, never>>,
    '//ecommerce/category': RouteRecordInfo<'//ecommerce/category', '/ecommerce/category', Record<never, never>, Record<never, never>>,
    '//ecommerce/checkout': RouteRecordInfo<'//ecommerce/checkout', '/ecommerce/checkout', Record<never, never>, Record<never, never>>,
    '//ecommerce/order-history': RouteRecordInfo<'//ecommerce/order-history', '/ecommerce/order-history', Record<never, never>, Record<never, never>>,
    '//ecommerce/product': RouteRecordInfo<'//ecommerce/product', '/ecommerce/product', Record<never, never>, Record<never, never>>,
    '//ecommerce/promo': RouteRecordInfo<'//ecommerce/promo', '/ecommerce/promo', Record<never, never>, Record<never, never>>,
    '//ecommerce/storefront': RouteRecordInfo<'//ecommerce/storefront', '/ecommerce/storefront', Record<never, never>, Record<never, never>>,
    '//ecommerce/workspace': RouteRecordInfo<'//ecommerce/workspace', '/ecommerce/workspace', Record<never, never>, Record<never, never>>,
    '//home': RouteRecordInfo<'//home', '/home', Record<never, never>, Record<never, never>>,
    '//portal/model': RouteRecordInfo<'//portal/model', '/portal/model', Record<never, never>, Record<never, never>>,
    '//pricing': RouteRecordInfo<'//pricing', '/pricing', Record<never, never>, Record<never, never>>,
    '//settings': RouteRecordInfo<'//settings', '/settings', Record<never, never>, Record<never, never>>,
    '//user/settings': RouteRecordInfo<'//user/settings', '/user/settings', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/model-framework': RouteRecordInfo<'/model-framework', '/model-framework', Record<never, never>, Record<never, never>>,
    '/splashscreen': RouteRecordInfo<'/splashscreen', '/splashscreen', Record<never, never>, Record<never, never>>,
  }
}
